[package]
name = "splicer-tool-sdk"
version = "0.1.0"
edition = "2021"
authors = ["Elizabeth Gilbert"]
description = "Rust SDK for building splicer middleware and downstream tools."
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/ejrgilbert/splicer"
keywords = ["wasm", "WebAssembly", "components", "splicer"]
categories = ["wasm"]

[workspace]

[dependencies]
splicer-tool-sdk-derive = { version = "0.1.0", path = "../splicer-tool-sdk-derive" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
