[package]
name = "otel-bare-logs"
version = "0.2.1"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.51.0", features = ["default", "async-spawn", "inter-task-wakeup", "async"] }

[build-dependencies]
builtin-protocol = { package = "splicer-builtin-protocol", path = "../builtin-protocol", version = "0.2.0" }
