//! `build.rs` helper invoked by each builtin to:
//!
//! - Validate its `manifest.toml`.
//! - Copy the manifest bytes into `$OUT_DIR/manifest.toml` (so the
//!   emitted Rust can `include_bytes!` it from a stable path) and
//!   write `$OUT_DIR/builtin_config_codegen.rs` for the builtin's
//!   `lib.rs` to `include!`. The emitted file declares:
//!     - `static SPLICER_BUILTIN_MANIFEST` attributed with
//!       `#[link_section = "splicer-builtin-manifest"]` — lands the
//!       TOML bytes verbatim in a wasm custom section, picked up by
//!       `splicer builtin <name>` and the splice-time validator.
//!     - `pub mod config { ... }` — one typed accessor per declared
//!       key. Defaults live in `manifest.toml` only.

use std::path::Path;

use crate::{section_name_for, ConfigKey, KeyType, Manifest};

/// Read + validate `manifest.toml` at `manifest_path`, then write the
/// codegen output to `$OUT_DIR/builtin_config_codegen.rs`.
///
/// Call from a builtin's `build.rs` (`fn main()`) with a path relative
/// to the crate root, e.g. `codegen(Path::new("manifest.toml"))`. The
/// builtin's canonical name is derived from `$CARGO_MANIFEST_DIR`'s
/// last path segment, matching splicer's directory-as-canonical-name
/// convention (see `build.rs::generate_builtin_manifest`).
pub fn codegen(manifest_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("builtin_config_codegen.rs");
    let manifest_copy = Path::new(&out_dir).join("manifest.toml");
    let builtin_name = builtin_name_from_env()?;

    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let src = std::fs::read_to_string(manifest_path).map_err(|e| {
        format!(
            "Failed to read manifest at {}: {e}",
            manifest_path.display(),
        )
    })?;
    let manifest = Manifest::from_toml(&src)?;
    std::fs::write(&manifest_copy, &src).map_err(|e| {
        format!(
            "Failed to copy manifest to {}: {e}",
            manifest_copy.display()
        )
    })?;

    let mut out = String::new();
    out.push_str("// Auto-generated by builtin-manifest. Do not edit.\n\n");
    emit_link_section_static(&mut out, src.len(), &builtin_name);
    out.push('\n');
    emit_config_module(&mut out, &manifest);

    std::fs::write(&dest, out)
        .map_err(|e| format!("Failed to write codegen output to {}: {e}", dest.display()))?;
    Ok(())
}

/// Splicer treats the builtin's directory name as canonical (it's
/// what users put in YAML and what the OCI publish step uses).
/// `CARGO_MANIFEST_DIR` is the absolute path to the crate root; its
/// final component is therefore the directory name.
fn builtin_name_from_env() -> Result<String, String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .map_err(|e| format!("CARGO_MANIFEST_DIR not set: {e}"))?;
    Path::new(&manifest_dir)
        .file_name()
        .and_then(|s| s.to_str())
        .map(|s| s.to_string())
        .ok_or_else(|| {
            format!("CARGO_MANIFEST_DIR ({manifest_dir}) has no extractable final component")
        })
}

fn emit_link_section_static(out: &mut String, payload_len: usize, builtin_name: &str) {
    let section = section_name_for(builtin_name);
    out.push_str(
        "/// Manifest bytes attached as a wasm custom section. Splicer\n\
         /// finds this section by name via `wasmparser`; the bytes never\n\
         /// touch linear memory at runtime. The `used` attribute keeps the\n\
         /// linker from dropping the symbol, and the const block computes\n\
         /// the exact-size array so the section is sized to the TOML.\n",
    );
    out.push_str(&format!("#[link_section = \"{section}\"]\n"));
    out.push_str("#[used]\n");
    out.push_str(&format!(
        "static SPLICER_BUILTIN_MANIFEST: [u8; {payload_len}] = \
         *include_bytes!(concat!(env!(\"OUT_DIR\"), \"/manifest.toml\"));\n"
    ));
}

fn emit_config_module(out: &mut String, manifest: &Manifest) {
    out.push_str("/// Typed accessors generated from `manifest.toml`. Each accessor\n");
    out.push_str("/// reads the value once via the substrate import, parses to the\n");
    out.push_str("/// declared type, and caches the result. Defaults live in\n");
    out.push_str("/// `manifest.toml` — no inline literals.\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("pub mod config {\n");
    out.push_str("    use std::sync::OnceLock;\n\n");
    out.push_str("    fn lookup(key: &str) -> Option<String> {\n");
    // `crate::bindings::...` resolves at the include-site (lib.rs) where
    // every builtin places `mod bindings { wit_bindgen::generate!(...) }`.
    out.push_str("        crate::bindings::splicer::builtin_config::get::get(key)\n");
    out.push_str("    }\n\n");
    for key in &manifest.keys {
        emit_accessor(out, key);
        out.push('\n');
    }
    out.push_str("}\n");
}

fn emit_accessor(out: &mut String, key: &ConfigKey) {
    let fn_name = sanitize_ident(&key.name);
    let key_lit = escape_str(&key.name);
    let doc = key.doc.lines().next().unwrap_or("").trim();
    if !doc.is_empty() {
        out.push_str(&format!("    /// {doc}\n"));
    }
    match key.kind {
        KeyType::String => {
            let default = toml_default_string(&key.default);
            out.push_str(&format!("    pub fn {fn_name}() -> &'static str {{\n"));
            out.push_str("        static V: OnceLock<String> = OnceLock::new();\n");
            out.push_str("        V.get_or_init(|| {\n");
            out.push_str(&format!(
                "            lookup(\"{key_lit}\").unwrap_or_else(|| \"{}\".to_string())\n",
                escape_str(&default),
            ));
            out.push_str("        }).as_str()\n");
            out.push_str("    }\n");
        }
        KeyType::U32 => {
            let default = toml_default_u32(&key.default);
            out.push_str(&format!("    pub fn {fn_name}() -> u32 {{\n"));
            out.push_str("        static V: OnceLock<u32> = OnceLock::new();\n");
            out.push_str("        *V.get_or_init(|| {\n");
            out.push_str(&format!(
                "            lookup(\"{key_lit}\").and_then(|s| s.parse::<u32>().ok()).unwrap_or({default}u32)\n",
            ));
            out.push_str("        })\n");
            out.push_str("    }\n");
        }
        KeyType::F64 => {
            let default = toml_default_f64(&key.default);
            out.push_str(&format!("    pub fn {fn_name}() -> f64 {{\n"));
            out.push_str("        static V: OnceLock<f64> = OnceLock::new();\n");
            out.push_str("        *V.get_or_init(|| {\n");
            out.push_str(&format!(
                "            lookup(\"{key_lit}\").and_then(|s| s.parse::<f64>().ok()).unwrap_or({default}f64)\n",
            ));
            out.push_str("        })\n");
            out.push_str("    }\n");
        }
        KeyType::Bool => {
            let default = toml_default_bool(&key.default);
            out.push_str(&format!("    pub fn {fn_name}() -> bool {{\n"));
            out.push_str("        static V: OnceLock<bool> = OnceLock::new();\n");
            out.push_str("        *V.get_or_init(|| {\n");
            out.push_str(&format!(
                "            lookup(\"{key_lit}\").and_then(|s| s.parse::<bool>().ok()).unwrap_or({default})\n",
            ));
            out.push_str("        })\n");
            out.push_str("    }\n");
        }
    }
}

/// Map `foo-bar` → `foo_bar` so a kebab-case key becomes a valid
/// Rust identifier. Anything else odd is left to rustc to reject —
/// the manifest schema is small enough that we don't try to be
/// exhaustive here.
fn sanitize_ident(name: &str) -> String {
    name.replace('-', "_")
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn toml_default_string(v: &toml::Value) -> String {
    match v {
        toml::Value::String(s) => s.clone(),
        // `Manifest::validate` already rejected mismatches; reaching
        // a non-string here would mean a bug in the validator.
        _ => unreachable!("validated as string in Manifest::validate"),
    }
}

fn toml_default_u32(v: &toml::Value) -> u32 {
    match v {
        toml::Value::Integer(n) => *n as u32,
        _ => unreachable!("validated as u32 in Manifest::validate"),
    }
}

fn toml_default_f64(v: &toml::Value) -> f64 {
    match v {
        toml::Value::Float(f) => *f,
        toml::Value::Integer(n) => *n as f64,
        _ => unreachable!("validated as f64 in Manifest::validate"),
    }
}

fn toml_default_bool(v: &toml::Value) -> bool {
    match v {
        toml::Value::Boolean(b) => *b,
        _ => unreachable!("validated as bool in Manifest::validate"),
    }
}
