//! `build.rs` helper invoked by each builtin to:
//!
//! - Validate its `manifest.toml`.
//! - Copy the manifest bytes into `$OUT_DIR/manifest.toml` so the
//!   emitted Rust can `include_bytes!` it from a stable path.
//! - Write `$OUT_DIR/builtin_config_codegen.rs` for the builtin's
//!   `lib.rs` to `include!`. The emitted file declares:
//!     - `static SPLICER_BUILTIN_MANIFEST` attributed with
//!       `#[link_section]`-named-for-the-builtin — lands the TOML
//!       bytes verbatim in a wasm custom section.
//!     - `pub mod config { ... }` — one typed accessor per declared
//!       key, calling `wasm_wave::from_str` against a runtime-built
//!       `Type` and unwrapping to the Rust primitive / enum.

use std::path::Path;

use crate::{
    encode_toml_as_wave, section_name_for, ConfigKey, Manifest, TypeAst,
};

/// Read + validate `manifest.toml` at `manifest_path`, then write the
/// codegen output to `$OUT_DIR/builtin_config_codegen.rs`.
///
/// Call from a builtin's `build.rs` (`fn main()`) with a path relative
/// to the crate root, e.g. `codegen(Path::new("manifest.toml"))`. The
/// builtin's canonical name is derived from `$CARGO_MANIFEST_DIR`'s
/// last path segment, matching splicer's directory-as-canonical-name
/// convention (see `build.rs::generate_builtin_manifest`).
pub fn codegen(manifest_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("builtin_config_codegen.rs");
    let manifest_copy = Path::new(&out_dir).join("manifest.toml");
    let builtin_name = builtin_name_from_env()?;

    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let src = std::fs::read_to_string(manifest_path).map_err(|e| {
        format!(
            "Failed to read manifest at {}: {e}",
            manifest_path.display(),
        )
    })?;
    let manifest = Manifest::from_toml(&src)?;
    std::fs::write(&manifest_copy, &src).map_err(|e| {
        format!(
            "Failed to copy manifest to {}: {e}",
            manifest_copy.display()
        )
    })?;

    let mut out = String::new();
    out.push_str("// Auto-generated by builtin-manifest. Do not edit.\n\n");
    emit_link_section_static(&mut out, src.len(), &builtin_name);
    out.push('\n');
    emit_config_module(&mut out, &manifest)?;

    std::fs::write(&dest, out)
        .map_err(|e| format!("Failed to write codegen output to {}: {e}", dest.display()))?;
    Ok(())
}

/// Splicer treats the builtin's directory name as canonical (it's
/// what users put in YAML and what the OCI publish step uses).
/// `CARGO_MANIFEST_DIR` is the absolute path to the crate root; its
/// final component is therefore the directory name.
fn builtin_name_from_env() -> Result<String, String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .map_err(|e| format!("CARGO_MANIFEST_DIR not set: {e}"))?;
    Path::new(&manifest_dir)
        .file_name()
        .and_then(|s| s.to_str())
        .map(|s| s.to_string())
        .ok_or_else(|| {
            format!("CARGO_MANIFEST_DIR ({manifest_dir}) has no extractable final component")
        })
}

fn emit_link_section_static(out: &mut String, payload_len: usize, builtin_name: &str) {
    let section = section_name_for(builtin_name);
    out.push_str(
        "/// Manifest bytes attached as a wasm custom section. Splicer\n\
         /// finds this section by name via `wasmparser`; the bytes never\n\
         /// touch linear memory at runtime. The `used` attribute keeps the\n\
         /// linker from dropping the symbol.\n",
    );
    out.push_str(&format!("#[link_section = \"{section}\"]\n"));
    out.push_str("#[used]\n");
    out.push_str(&format!(
        "static SPLICER_BUILTIN_MANIFEST: [u8; {payload_len}] = \
         *include_bytes!(concat!(env!(\"OUT_DIR\"), \"/manifest.toml\"));\n"
    ));
}

fn emit_config_module(out: &mut String, manifest: &Manifest) -> Result<(), Box<dyn std::error::Error>> {
    out.push_str("/// Typed accessors generated from `manifest.toml`. Defaults live in\n");
    out.push_str("/// `manifest.toml` only; values come from the substrate import as WAVE\n");
    out.push_str("/// text and are parsed by hand-rolled per-type decoders below.\n");
    out.push_str("#[allow(dead_code, clippy::needless_borrow)]\n");
    out.push_str("pub mod config {\n");
    out.push_str("    use std::sync::OnceLock;\n\n");
    out.push_str("    fn lookup(key: &str) -> Option<String> {\n");
    out.push_str("        crate::bindings::splicer::builtin_config::get::get(key)\n");
    out.push_str("    }\n\n");
    if manifest
        .keys
        .iter()
        .any(|k| matches!(k.parsed_type().expect("manifest already validated"), TypeAst::String))
    {
        out.push_str(WAVE_STRING_DECODER);
        out.push('\n');
    }
    for key in &manifest.keys {
        emit_key(out, key)?;
        out.push('\n');
    }
    out.push_str("}\n");
    Ok(())
}

const WAVE_STRING_DECODER: &str = r#"    /// Decoder for the WAVE-text subset our splicer-side encoder
    /// (`builtin_manifest::encode_toml_as_wave`) emits: surrounding
    /// `"..."` quotes plus the standard `\"` `\\` `\n` `\r` `\t`
    /// `\xNN` `\u{NN}` escapes. Hand-rolled to keep the full
    /// `wasm-wave` crate (~300 KB on wasm32) out of every builtin.
    ///
    /// FUTURE: if/when the manifest schema grows to support compound
    /// types (records, variants, nested lists), this fallback will
    /// get unwieldy and the right answer is to swap the codegen back
    /// to `wasm_wave::from_str` and accept the dep cost. See the
    /// "Future: WAVE for compound types" notes in
    /// docs/TODO/builtin-config-substrate.md for the migration path.
    fn decode_wave_string(raw: &str) -> String {
        let inner = raw
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
            .expect("manifest-validated quoted string");
        let mut out = String::with_capacity(inner.len());
        let mut chars = inner.chars();
        while let Some(c) = chars.next() {
            if c != '\\' {
                out.push(c);
                continue;
            }
            match chars.next() {
                Some('"') => out.push('"'),
                Some('\\') => out.push('\\'),
                Some('n') => out.push('\n'),
                Some('r') => out.push('\r'),
                Some('t') => out.push('\t'),
                Some('x') => {
                    let h0 = chars.next().expect("hex digit").to_digit(16)
                        .expect("manifest-validated hex digit");
                    let h1 = chars.next().expect("hex digit").to_digit(16)
                        .expect("manifest-validated hex digit");
                    out.push(char::from_u32(h0 * 16 + h1).expect("valid char"));
                }
                Some('u') => {
                    let _open = chars.next(); // '{'
                    let mut hex = String::new();
                    for c in chars.by_ref() {
                        if c == '}' {
                            break;
                        }
                        hex.push(c);
                    }
                    let n = u32::from_str_radix(&hex, 16)
                        .expect("manifest-validated unicode escape");
                    out.push(char::from_u32(n).expect("valid char"));
                }
                other => panic!("unknown escape in manifest-validated string: {other:?}"),
            }
        }
        out
    }

"#;

fn emit_key(out: &mut String, key: &ConfigKey) -> Result<(), Box<dyn std::error::Error>> {
    let ty = key.parsed_type()?;
    let default_wave = encode_toml_as_wave(&key.default, &ty, key.case_insensitive)?;
    let fn_name = sanitize_ident(&key.name);
    let key_lit = escape_rust_str(&key.name);
    let default_lit = escape_rust_str(&default_wave);
    let doc = key.doc.lines().next().unwrap_or("").trim();
    if !doc.is_empty() {
        out.push_str(&format!("    /// {doc}\n"));
    }
    match &ty {
        TypeAst::Bool
        | TypeAst::U8
        | TypeAst::U16
        | TypeAst::U32
        | TypeAst::U64
        | TypeAst::S8
        | TypeAst::S16
        | TypeAst::S32
        | TypeAst::S64
        | TypeAst::F32
        | TypeAst::F64 => emit_numeric_accessor(out, &fn_name, &key_lit, &default_lit, &ty),
        TypeAst::Char => {
            // `char` isn't in our current vocabulary; reachable if a
            // future manifest declares it. Codegen panics so the
            // build fails loudly.
            return Err(format!(
                "key '{}': type `char` codegen not yet implemented",
                key.name
            )
            .into());
        }
        TypeAst::String => emit_string_accessor(out, &fn_name, &key_lit, &default_lit),
        TypeAst::Enum { cases } => emit_enum_accessor(out, &fn_name, &key_lit, &default_lit, cases),
        TypeAst::List(_) | TypeAst::Option(_) | TypeAst::Tuple(_) => {
            return Err(format!(
                "key '{}': compound-type codegen not yet implemented \
                 (see the wasm-wave fallback note in builtin-manifest)",
                key.name,
            )
            .into());
        }
    }
    Ok(())
}

fn rust_primitive(ty: &TypeAst) -> &'static str {
    match ty {
        TypeAst::Bool => "bool",
        TypeAst::U8 => "u8",
        TypeAst::U16 => "u16",
        TypeAst::U32 => "u32",
        TypeAst::U64 => "u64",
        TypeAst::S8 => "i8",
        TypeAst::S16 => "i16",
        TypeAst::S32 => "i32",
        TypeAst::S64 => "i64",
        TypeAst::F32 => "f32",
        TypeAst::F64 => "f64",
        _ => unreachable!("called on non-primitive"),
    }
}

fn emit_numeric_accessor(out: &mut String, fn_name: &str, key_lit: &str, default_lit: &str, ty: &TypeAst) {
    let rust_ty = rust_primitive(ty);
    out.push_str(&format!("    pub fn {fn_name}() -> {rust_ty} {{\n"));
    out.push_str(&format!(
        "        static V: OnceLock<{rust_ty}> = OnceLock::new();\n"
    ));
    out.push_str("        *V.get_or_init(|| {\n");
    out.push_str(&format!(
        "            lookup(\"{key_lit}\").unwrap_or_else(|| \"{default_lit}\".to_string())\n"
    ));
    out.push_str(&format!(
        "                .parse::<{rust_ty}>().expect(\"manifest-validated {rust_ty}\")\n"
    ));
    out.push_str("        })\n");
    out.push_str("    }\n");
}

fn emit_string_accessor(out: &mut String, fn_name: &str, key_lit: &str, default_lit: &str) {
    out.push_str(&format!("    pub fn {fn_name}() -> &'static str {{\n"));
    out.push_str("        static V: OnceLock<String> = OnceLock::new();\n");
    out.push_str("        let v = V.get_or_init(|| {\n");
    out.push_str(&format!(
        "            let raw = lookup(\"{key_lit}\").unwrap_or_else(|| \"{default_lit}\".to_string());\n"
    ));
    out.push_str("            decode_wave_string(&raw)\n");
    out.push_str("        });\n");
    // `String::as_str` qualified to dodge the recent stdlib name
    // clash with `str::as_str`.
    out.push_str("        String::as_str(v)\n");
    out.push_str("    }\n");
}

fn emit_enum_accessor(out: &mut String, fn_name: &str, key_lit: &str, default_lit: &str, cases: &[String]) {
    out.push_str(&format!("    pub fn {fn_name}() -> &'static str {{\n"));
    out.push_str("        static V: OnceLock<&'static str> = OnceLock::new();\n");
    out.push_str("        *V.get_or_init(|| {\n");
    out.push_str(&format!(
        "            let raw = lookup(\"{key_lit}\").unwrap_or_else(|| \"{default_lit}\".to_string());\n"
    ));
    out.push_str("            match raw.as_str() {\n");
    for c in cases {
        let lit = escape_rust_str(c);
        out.push_str(&format!("                \"{lit}\" => \"{lit}\",\n"));
    }
    out.push_str("                _ => panic!(\"manifest-validated enum value\"),\n");
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("    }\n");
}

fn sanitize_ident(name: &str) -> String {
    name.replace('-', "_")
}

fn escape_rust_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
