//! `build.rs` helper invoked by each builtin to:
//!
//! - Validate its `manifest.toml`.
//! - Copy the manifest bytes into `$OUT_DIR/manifest.toml` so the
//!   emitted Rust can `include_bytes!` it from a stable path.
//! - Write `$OUT_DIR/builtin_config_codegen.rs` for the builtin's
//!   `lib.rs` to `include!`. The emitted file declares:
//!     - `static SPLICER_BUILTIN_MANIFEST` attributed with
//!       `#[link_section]`-named-for-the-builtin — lands the TOML
//!       bytes verbatim in a wasm custom section.
//!     - `pub mod config { ... }` — one typed accessor per declared
//!       key, decoding the substrate's WAVE text into the typed Rust
//!       value via hand-rolled per-type decoders.
//!
//! Codegen is built as a `proc_macro2::TokenStream` via the `quote!`
//! macro and serialized to disk. The generated file is dense
//! single-line tokens; `cat $OUT_DIR/builtin_config_codegen.rs` to
//! eyeball it during debugging.

use std::path::Path;

use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::{encode_toml_as_wave, section_name_for, ConfigKey, Manifest, TypeAst};

/// Read + validate `manifest.toml` at `manifest_path`, then write the
/// codegen output to `$OUT_DIR/builtin_config_codegen.rs`.
///
/// Call from a builtin's `build.rs` (`fn main()`) with a path relative
/// to the crate root, e.g. `codegen(Path::new("manifest.toml"))`. The
/// builtin's canonical name is derived from `$CARGO_MANIFEST_DIR`'s
/// last path segment, matching splicer's directory-as-canonical-name
/// convention (see `build.rs::generate_builtin_manifest`).
pub fn codegen(manifest_path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("builtin_config_codegen.rs");
    let manifest_copy = Path::new(&out_dir).join("manifest.toml");
    let builtin_name = builtin_name_from_env()?;

    println!("cargo::rerun-if-changed={}", manifest_path.display());

    let src = std::fs::read_to_string(manifest_path).map_err(|e| {
        format!(
            "Failed to read manifest at {}: {e}",
            manifest_path.display()
        )
    })?;
    let manifest = Manifest::from_toml(&src)?;
    std::fs::write(&manifest_copy, &src).map_err(|e| {
        format!(
            "Failed to copy manifest to {}: {e}",
            manifest_copy.display()
        )
    })?;

    let tokens = build_codegen(&manifest, src.len(), &builtin_name)?;
    // `quote!` emits dense single-line output; prepend a leading
    // "auto-generated" banner as a regular comment so a `cat` of the
    // file is at least labeled.
    let mut body = String::from("// Auto-generated by builtin-manifest. Do not edit.\n");
    body.push_str(&tokens.to_string());
    body.push('\n');

    std::fs::write(&dest, body)
        .map_err(|e| format!("Failed to write codegen output to {}: {e}", dest.display()))?;
    Ok(())
}

/// Splicer treats the builtin's directory name as canonical (it's
/// what users put in YAML and what the OCI publish step uses).
/// `CARGO_MANIFEST_DIR` is the absolute path to the crate root; its
/// final component is therefore the directory name.
fn builtin_name_from_env() -> Result<String, String> {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .map_err(|e| format!("CARGO_MANIFEST_DIR not set: {e}"))?;
    Path::new(&manifest_dir)
        .file_name()
        .and_then(|s| s.to_str())
        .map(|s| s.to_string())
        .ok_or_else(|| {
            format!("CARGO_MANIFEST_DIR ({manifest_dir}) has no extractable final component")
        })
}

fn build_codegen(
    manifest: &Manifest,
    payload_len: usize,
    builtin_name: &str,
) -> Result<TokenStream, Box<dyn std::error::Error>> {
    let section_static = build_section_static(payload_len, builtin_name);
    let module = build_config_module(manifest)?;
    Ok(quote! {
        #section_static
        #module
    })
}

fn build_section_static(payload_len: usize, builtin_name: &str) -> TokenStream {
    let section = section_name_for(builtin_name);
    let len = proc_macro2::Literal::usize_unsuffixed(payload_len);
    quote! {
        #[doc = " Manifest bytes attached as a wasm custom section. Splicer finds it"]
        #[doc = " by name via `wasmparser`; the bytes never touch linear memory at"]
        #[doc = " runtime. `#[used]` keeps the linker from dropping the symbol."]
        #[link_section = #section]
        #[used]
        static SPLICER_BUILTIN_MANIFEST: [u8; #len] =
            *include_bytes!(concat!(env!("OUT_DIR"), "/manifest.toml"));
    }
}

fn build_config_module(manifest: &Manifest) -> Result<TokenStream, Box<dyn std::error::Error>> {
    let needs_string_decoder = manifest.keys.iter().any(|k| {
        matches!(
            k.parsed_type().expect("manifest already validated"),
            TypeAst::String
        )
    });
    let decoder = if needs_string_decoder {
        build_wave_string_decoder()
    } else {
        TokenStream::new()
    };
    let mut type_decls = Vec::new();
    let mut accessors = Vec::new();
    for key in &manifest.keys {
        let ty = key.parsed_type().expect("manifest already validated");
        if let TypeAst::Enum { cases } = &ty {
            type_decls.push(build_enum_type(&key.name, cases));
        }
        accessors.push(build_accessor(key)?);
    }
    Ok(quote! {
        #[doc = " Typed accessors generated from `manifest.toml`. Defaults live in"]
        #[doc = " `manifest.toml` only; values come from the substrate import as WAVE"]
        #[doc = " text and are parsed by hand-rolled per-type decoders below."]
        #[allow(dead_code, clippy::needless_borrow)]
        pub mod config {
            use std::sync::OnceLock;

            fn lookup(key: &str) -> Option<String> {
                crate::bindings::splicer::builtin_config::get::get(key)
            }

            #(#type_decls)*

            #decoder

            #(#accessors)*
        }
    })
}

/// Synthesize a `pub enum <PascalCase-key-name>` for an
/// `enum { ... }`-typed key. Variants are PascalCase'd from the
/// manifest cases. `Copy` so the accessor can return by value;
/// `Debug`/`PartialEq` for downstream `match`/`assert_eq!` ergonomics.
fn build_enum_type(key_name: &str, cases: &[String]) -> TokenStream {
    let type_name = format_ident!("{}", pascal_case(key_name));
    let variants = cases.iter().map(|c| {
        let variant = format_ident!("{}", pascal_case(c));
        let case_doc = format!(" Manifest case `{c}`.");
        quote! {
            #[doc = #case_doc]
            #variant,
        }
    });
    quote! {
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum #type_name {
            #(#variants)*
        }
    }
}

/// Map kebab-case / snake_case identifiers to UpperCamelCase (`info`
/// → `Info`, `warn-error` → `WarnError`, `span_kind` → `SpanKind`).
fn pascal_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut upper_next = true;
    for c in name.chars() {
        if c == '-' || c == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(c.to_uppercase());
            upper_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

/// Hand-rolled decoder for the WAVE-text subset our splicer-side
/// encoder emits: `"..."` quotes plus standard `\"` `\\` `\n` `\r`
/// `\t` `\xNN` `\u{NN}` escapes. Skips the full `wasm-wave` crate
/// (~300 KB on wasm32) at the cost of staying in lock-step with the
/// canonical encoder for the subset we care about. When the manifest
/// schema grows to support compound types, swap this back for
/// `wasm_wave::from_str` and accept the dep cost.
fn build_wave_string_decoder() -> TokenStream {
    quote! {
        fn decode_wave_string(raw: &str) -> String {
            let inner = raw
                .strip_prefix('"')
                .and_then(|s| s.strip_suffix('"'))
                .expect("manifest-validated quoted string");
            let mut out = String::with_capacity(inner.len());
            let mut chars = inner.chars();
            while let Some(c) = chars.next() {
                if c != '\\' {
                    out.push(c);
                    continue;
                }
                match chars.next() {
                    Some('"') => out.push('"'),
                    Some('\\') => out.push('\\'),
                    Some('n') => out.push('\n'),
                    Some('r') => out.push('\r'),
                    Some('t') => out.push('\t'),
                    Some('x') => {
                        let h0 = chars
                            .next()
                            .expect("hex digit")
                            .to_digit(16)
                            .expect("manifest-validated hex digit");
                        let h1 = chars
                            .next()
                            .expect("hex digit")
                            .to_digit(16)
                            .expect("manifest-validated hex digit");
                        out.push(char::from_u32(h0 * 16 + h1).expect("valid char"));
                    }
                    Some('u') => {
                        let _open = chars.next(); // '{'
                        let mut hex = String::new();
                        for c in chars.by_ref() {
                            if c == '}' {
                                break;
                            }
                            hex.push(c);
                        }
                        let n = u32::from_str_radix(&hex, 16)
                            .expect("manifest-validated unicode escape");
                        out.push(char::from_u32(n).expect("valid char"));
                    }
                    other => panic!("unknown escape in manifest-validated string: {other:?}"),
                }
            }
            out
        }
    }
}

fn build_accessor(key: &ConfigKey) -> Result<TokenStream, Box<dyn std::error::Error>> {
    let ty = key.parsed_type()?;
    let default_wave = encode_toml_as_wave(&key.default, &ty, key.case_insensitive)?;
    let fn_name = format_ident!("{}", sanitize_ident(&key.name));
    let key_lit = key.name.as_str();
    let default_lit = default_wave.as_str();
    let doc = key.doc.lines().next().unwrap_or("").trim();
    let doc_attr = if doc.is_empty() {
        TokenStream::new()
    } else {
        let line = format!(" {doc}");
        quote! { #[doc = #line] }
    };

    match &ty {
        TypeAst::Bool
        | TypeAst::U8
        | TypeAst::U16
        | TypeAst::U32
        | TypeAst::U64
        | TypeAst::S8
        | TypeAst::S16
        | TypeAst::S32
        | TypeAst::S64
        | TypeAst::F32
        | TypeAst::F64 => Ok(build_numeric_accessor(
            &fn_name,
            key_lit,
            default_lit,
            &ty,
            doc_attr,
        )),
        TypeAst::Char => Err(format!(
            "key '{}': type `char` codegen not yet implemented",
            key.name
        )
        .into()),
        TypeAst::String => Ok(build_string_accessor(
            &fn_name,
            key_lit,
            default_lit,
            doc_attr,
        )),
        TypeAst::Enum { cases } => {
            let type_name = format_ident!("{}", pascal_case(&key.name));
            Ok(build_enum_accessor(
                &fn_name,
                &type_name,
                key_lit,
                default_lit,
                cases,
                doc_attr,
            ))
        }
        TypeAst::List(_) | TypeAst::Option(_) | TypeAst::Tuple(_) => Err(format!(
            "key '{}': compound-type codegen not yet implemented \
             (see the wasm-wave fallback note in builtin-manifest)",
            key.name,
        )
        .into()),
    }
}

fn build_numeric_accessor(
    fn_name: &proc_macro2::Ident,
    key_lit: &str,
    default_lit: &str,
    ty: &TypeAst,
    doc_attr: TokenStream,
) -> TokenStream {
    let rust_ty = format_ident!("{}", rust_primitive(ty));
    let expect_msg = format!("manifest-validated {}", rust_primitive(ty));
    quote! {
        #doc_attr
        pub fn #fn_name() -> #rust_ty {
            static V: OnceLock<#rust_ty> = OnceLock::new();
            *V.get_or_init(|| {
                lookup(#key_lit)
                    .unwrap_or_else(|| #default_lit.to_string())
                    .parse::<#rust_ty>()
                    .expect(#expect_msg)
            })
        }
    }
}

fn build_string_accessor(
    fn_name: &proc_macro2::Ident,
    key_lit: &str,
    default_lit: &str,
    doc_attr: TokenStream,
) -> TokenStream {
    quote! {
        #doc_attr
        pub fn #fn_name() -> &'static str {
            static V: OnceLock<String> = OnceLock::new();
            let v = V.get_or_init(|| {
                let raw = lookup(#key_lit)
                    .unwrap_or_else(|| #default_lit.to_string());
                decode_wave_string(&raw)
            });
            // `String::as_str` qualified to dodge the recent stdlib
            // name clash with `str::as_str`.
            String::as_str(v)
        }
    }
}

fn build_enum_accessor(
    fn_name: &proc_macro2::Ident,
    type_name: &proc_macro2::Ident,
    key_lit: &str,
    default_lit: &str,
    cases: &[String],
    doc_attr: TokenStream,
) -> TokenStream {
    let arms = cases.iter().map(|c| {
        let lit = c.as_str();
        let variant = format_ident!("{}", pascal_case(c));
        quote! { #lit => #type_name::#variant, }
    });
    quote! {
        #doc_attr
        pub fn #fn_name() -> #type_name {
            static V: OnceLock<#type_name> = OnceLock::new();
            *V.get_or_init(|| {
                let raw = lookup(#key_lit)
                    .unwrap_or_else(|| #default_lit.to_string());
                match raw.as_str() {
                    #(#arms)*
                    _ => unreachable!("splice-time validation guarantees a declared case"),
                }
            })
        }
    }
}

fn rust_primitive(ty: &TypeAst) -> &'static str {
    match ty {
        TypeAst::Bool => "bool",
        TypeAst::U8 => "u8",
        TypeAst::U16 => "u16",
        TypeAst::U32 => "u32",
        TypeAst::U64 => "u64",
        TypeAst::S8 => "i8",
        TypeAst::S16 => "i16",
        TypeAst::S32 => "i32",
        TypeAst::S64 => "i64",
        TypeAst::F32 => "f32",
        TypeAst::F64 => "f64",
        _ => unreachable!("called on non-primitive"),
    }
}

fn sanitize_ident(name: &str) -> String {
    name.replace('-', "_")
}
