//! `#[derive(TypedFromCells)]`: emit a `TypedFromCells` impl for a
//! Rust type generated by `wit-bindgen` from a target WIT.
//!
//! Re-exported from `splicer-tool-sdk` as
//! `splicer_tool_sdk::TypedFromCells` so consumers depend on one
//! crate and pick up both the trait and the derive. Use it via
//! `wit-bindgen`'s `additional_derives:` argument so every record /
//! variant / enum the wrapped target's WIT defines picks up a decode
//! impl automatically.
//!
//! v1 scope: records (named-field structs), enums (unit-only Rust
//! enums, matching WIT `enum`), and variants (Rust enums whose cases
//! are unit or one-payload, matching WIT `variant`). Resources are
//! deferred to v2; flags are deferred (wit-bindgen's bitflags shape
//! needs separate handling).

use heck::ToKebabCase;
use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::{parse_macro_input, Data, DataEnum, DataStruct, DeriveInput, Fields, Ident};

#[proc_macro_derive(TypedFromCells)]
pub fn derive_typed_from_cells(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;
    let body = match &input.data {
        Data::Struct(s) => derive_record(name, s),
        Data::Enum(e) => derive_enum_or_variant(name, e),
        Data::Union(_) => {
            return syn::Error::new_spanned(
                &input.ident,
                "TypedFromCells does not support unions",
            )
            .to_compile_error()
            .into();
        }
    };
    let body = match body {
        Ok(b) => b,
        Err(e) => return e.to_compile_error().into(),
    };
    quote! {
        #[automatically_derived]
        impl ::splicer_tool_sdk::TypedFromCells for #name {
            fn from_cells(
                tree: &::splicer_tool_sdk::FieldTree,
                root: u32,
            ) -> ::core::result::Result<Self, ::splicer_tool_sdk::FromCellsError> {
                #body
            }
        }
    }
    .into()
}

/// Decode a WIT `record` from `Cell::RecordOf`.
fn derive_record(name: &Ident, s: &DataStruct) -> syn::Result<TokenStream2> {
    let fields = match &s.fields {
        Fields::Named(named) => &named.named,
        Fields::Unit => {
            // Empty record: still emit a working impl that just
            // verifies the cell is a `RecordOf` and constructs `Self`.
            return Ok(quote! {
                let cell = ::splicer_tool_sdk::typed_from_cells::__get_cell(tree, root)?;
                match cell {
                    ::splicer_tool_sdk::Cell::RecordOf(_) => ::core::result::Result::Ok(Self),
                    other => ::core::result::Result::Err(
                        ::splicer_tool_sdk::FromCellsError::new(
                            format!("expected RecordOf at cell {root}, got {other:?}")
                        )
                    ),
                }
            });
        }
        Fields::Unnamed(_) => {
            return Err(syn::Error::new_spanned(
                name,
                "TypedFromCells: tuple structs are not supported; use a named-field record",
            ));
        }
    };

    let field_decoders = fields.iter().map(|f| {
        let ident = f.ident.as_ref().expect("named field");
        let ty = &f.ty;
        let wit_name = ident.to_string().to_kebab_case();
        quote! {
            let #ident = {
                let (_, child) = info.fields.iter()
                    .find(|(n, _)| n == #wit_name)
                    .ok_or_else(|| ::splicer_tool_sdk::FromCellsError::new(
                        format!("record field '{}' missing", #wit_name)
                    ))?;
                <#ty as ::splicer_tool_sdk::TypedFromCells>::from_cells(tree, *child)?
            };
        }
    });
    let field_names = fields.iter().map(|f| f.ident.as_ref().expect("named field"));

    let type_name = name.to_string();
    Ok(quote! {
        let cell = ::splicer_tool_sdk::typed_from_cells::__get_cell(tree, root)?;
        let side_idx = match cell {
            ::splicer_tool_sdk::Cell::RecordOf(i) => *i,
            other => return ::core::result::Result::Err(
                ::splicer_tool_sdk::FromCellsError::new(
                    format!("expected RecordOf for {} at cell {root}, got {other:?}", #type_name)
                )
            ),
        };
        let info = tree.record_infos.get(side_idx as usize).ok_or_else(|| {
            ::splicer_tool_sdk::FromCellsError::new(
                format!("record_infos[{side_idx}] out of bounds (len = {})", tree.record_infos.len())
            )
        })?;
        #(#field_decoders)*
        ::core::result::Result::Ok(Self { #(#field_names),* })
    })
}

/// Decide whether this Rust enum maps to a WIT `enum` (all unit
/// variants) or `variant` (at least one variant with a payload), and
/// emit the appropriate decoder. A unit-only Rust enum can be
/// encoded either way at the cells layer (a WIT `variant` whose
/// cases happen to be all unit), so the unit-only decoder accepts
/// both `Cell::EnumCase` and `Cell::VariantCase`.
fn derive_enum_or_variant(name: &Ident, e: &DataEnum) -> syn::Result<TokenStream2> {
    let all_unit = e.variants.iter().all(|v| matches!(v.fields, Fields::Unit));
    if all_unit {
        derive_unit_enum(name, e)
    } else {
        derive_variant(name, e)
    }
}

/// Unit-only enum: every variant has no payload. Accept either
/// `Cell::EnumCase` (WIT `enum`) or `Cell::VariantCase` with no
/// payload (WIT `variant` happens to have all-unit cases).
fn derive_unit_enum(name: &Ident, e: &DataEnum) -> syn::Result<TokenStream2> {
    let type_name = name.to_string();
    let arms = e.variants.iter().map(|v| {
        let variant_ident = &v.ident;
        let wit_case = variant_ident.to_string().to_kebab_case();
        quote! { #wit_case => ::core::result::Result::Ok(Self::#variant_ident), }
    });

    Ok(quote! {
        let cell = ::splicer_tool_sdk::typed_from_cells::__get_cell(tree, root)?;
        let case_name: &str = match cell {
            ::splicer_tool_sdk::Cell::EnumCase(i) => {
                let info = tree.enum_infos.get(*i as usize).ok_or_else(|| {
                    ::splicer_tool_sdk::FromCellsError::new(
                        format!("enum_infos[{i}] out of bounds (len = {})", tree.enum_infos.len())
                    )
                })?;
                &info.case_name
            }
            ::splicer_tool_sdk::Cell::VariantCase(i) => {
                let info = tree.variant_infos.get(*i as usize).ok_or_else(|| {
                    ::splicer_tool_sdk::FromCellsError::new(
                        format!("variant_infos[{i}] out of bounds (len = {})", tree.variant_infos.len())
                    )
                })?;
                if info.payload.is_some() {
                    return ::core::result::Result::Err(
                        ::splicer_tool_sdk::FromCellsError::new(
                            format!("{} expected unit-only case, got payload-carrying case '{}'", #type_name, info.case_name)
                        )
                    );
                }
                &info.case_name
            }
            other => return ::core::result::Result::Err(
                ::splicer_tool_sdk::FromCellsError::new(
                    format!("expected EnumCase or VariantCase for {} at cell {root}, got {other:?}", #type_name)
                )
            ),
        };
        match case_name {
            #(#arms)*
            other => ::core::result::Result::Err(
                ::splicer_tool_sdk::FromCellsError::new(
                    format!("unknown case '{other}' for {}", #type_name)
                )
            ),
        }
    })
}

/// Variant: at least one Rust enum variant carries a payload.
/// WIT variants always have either zero or one payload per case
/// (multi-field payloads are expressed via record types).
fn derive_variant(name: &Ident, e: &DataEnum) -> syn::Result<TokenStream2> {
    let type_name = name.to_string();
    let arms: syn::Result<Vec<TokenStream2>> = e.variants.iter().map(|v| {
        let variant_ident = &v.ident;
        let wit_case = variant_ident.to_string().to_kebab_case();
        match &v.fields {
            Fields::Unit => Ok(quote! {
                #wit_case => {
                    if info.payload.is_some() {
                        return ::core::result::Result::Err(
                            ::splicer_tool_sdk::FromCellsError::new(
                                format!("{}::{} expects no payload, got one", #type_name, #wit_case)
                            )
                        );
                    }
                    ::core::result::Result::Ok(Self::#variant_ident)
                }
            }),
            Fields::Unnamed(fields) if fields.unnamed.len() == 1 => {
                let ty = &fields.unnamed.first().unwrap().ty;
                Ok(quote! {
                    #wit_case => {
                        let payload = info.payload.ok_or_else(|| {
                            ::splicer_tool_sdk::FromCellsError::new(
                                format!("{}::{} expects payload, got none", #type_name, #wit_case)
                            )
                        })?;
                        let value = <#ty as ::splicer_tool_sdk::TypedFromCells>::from_cells(tree, payload)?;
                        ::core::result::Result::Ok(Self::#variant_ident(value))
                    }
                })
            }
            _ => Err(syn::Error::new_spanned(
                variant_ident,
                "TypedFromCells: variant cases must be unit or single-unnamed-field (matching WIT variant shape)",
            )),
        }
    }).collect();
    let arms = arms?;

    Ok(quote! {
        let cell = ::splicer_tool_sdk::typed_from_cells::__get_cell(tree, root)?;
        let info = match cell {
            ::splicer_tool_sdk::Cell::VariantCase(i) => {
                tree.variant_infos.get(*i as usize).ok_or_else(|| {
                    ::splicer_tool_sdk::FromCellsError::new(
                        format!("variant_infos[{i}] out of bounds (len = {})", tree.variant_infos.len())
                    )
                })?
            }
            other => return ::core::result::Result::Err(
                ::splicer_tool_sdk::FromCellsError::new(
                    format!("expected VariantCase for {} at cell {root}, got {other:?}", #type_name)
                )
            ),
        };
        match info.case_name.as_str() {
            #(#arms)*
            other => ::core::result::Result::Err(
                ::splicer_tool_sdk::FromCellsError::new(
                    format!("unknown variant case '{other}' for {}", #type_name)
                )
            ),
        }
    })
}
